name: Git Hook Message Discord

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'PR Patch Notes: \\n {{ EVENT_PAYLOAD.event.pull_request.body }}'